logger/Dockerfile, logger/logger.sh, logger/nodelogger.yaml
- Logger can take a container as an argument & collect logs until it exists
- The node (systemd) logs are now stored inside the <test-specific> dir on hosts instead of /mnt
- Dockerfile updates (base image version changed to ubuntu:16.04)
- The test container is placed in the logger entrypoint command specified in the jobs under the existing duration argument (-d)
- The pod name & namespace should be passed to the logger via ENV
- Example litmus jobs using these enhancements are described in https://github.com/openebs/litmus/pull/114
=> Add capabilities to collect logs for duration of a specific container

custom-liveness-client/custom-liveness.yml, custom-liveness-client/liveness.py
This commit does the following:
- Changes the custom-liveness script in order to work like a standard liveness script in which following considerations have been taken:
1.INIT_WAIT_DELAY
2.INIT_RETRY_COUNT
3.LIVENESS_PERIOD_SECONDS
4.LIVENESS_TIMEOUT_SECONDS
5.LIVENESS_RETRY_COUNT
- Now this script is able to accept liveness-specific params as an ENV-VAR.
=> Modified the custom liveness script

.travis.yml, Makefile
- Integrate travis-CI to build/push the test images 
- Some of the test images (jenkins-client, mongo-client, postgres-client, jupyter-client) are undergoing changes and will be added into the makefile as a separate PR
=> chore(ci): integrate with travis-CI to build & push the test images

tpcc-client/tpcc-mysql/tpcc-runner.sh
- The percona db-init check sometimes takes longer depending upon the underlying storage. Setting a slightly larger upper-bound for the db init wait time 
=> refactor(bash): increase retry count for database init check on mysql

libiscsi/Dockerfile
**What this PR does / why we need it**:  Removes extra `RUN` statement from the Dockerfile (best practices).
**Which issue this PR fixes**: #40.
**Special notes for your reviewer**: N/A
=> libiscsi: Update Dockerfile (#40).

mongo-client/Dockerfile, mysql-client/Dockerfile
Signed-off-by: Bilal.M.K <bilal.k@endurance.com>
Fixes https://github.com/openebs/test-tools/issues/41
1. Cleanup apt Cache and reduce the docker layer
2. sysbench-mongo support without MySQL support
Fixes https://github.com/openebs/test-tools/issues/42
1. Use alpine base image
=> Improve the dockerfile

mysql-client/mysql-liveness-check.sh
mysql-client uses 'timeout' command to check the liveness of the percona application. Due to wrong parameters for 'timeout' command, it always returns error.
This PR is to fix the parameters of timeout command, and, to have 5 seconds as timeout value.
Signed-off-by: Vishnu Itta <vitta@mayadata.io>
=> fix(mysql_client): fixing timeout command parameters

mysql-client/db-cred.cnf, mysql-client/mysql-liveness-check.sh, mysql-client/mysql-liveness-check.yaml
Enhances the mysql liveness script & K8s job: 
- Accept database credentials from env instead of a conf file
- Use timeout for database init check
- Update usage to segregate mandatory & optional env
- Update K8s liveness job with new env, service fqdn & entrypoint
=> refactor(bash)(liveness): enhance mysql liveness script

custom-percona/Dockerfile, custom-percona/docker-entrypoint.sh, custom-percona/sql-test.sh
- Percona no longer uses debian:jessie as the base image. It is updated w/ latest (debian:stretch)
- Update the entrypoint script as per latest 5.7 percona minor version
- Include liveness script to be used as a K8s liveness probe
=> (refactor)(docker): update custom-percona image to latest version & include liveness script

custom-percona/Dockerfile, custom-percona/mysqld.cnf, custom-percona/sql-test.sh
- Increase efficiency of the liveness script by performing CRUD on percona DB instead of just simple table write/drop database
- Use innodb_flush_method to O_DIRECT (base image debian:stretch supports it) in order to perform unbuffered I/O for log writes
- Perform `sync` after write ops to ensure data in client fs is pushed to persistent disk
- Update percona MINOR_VERSION 
- `sync_binlog=1` is a surer way to flush every transaction's data to disk (along w/ the `innodb_flush_log_at_trx_commit=1`, which is …
=> (refactor)(image): enhance liveness load w/ DB CRUD operations 

.travis.yml, fio/fio_runner.sh, fio/templates/file/basic-read, fio/templates/file/fill_fs, fio/templates/file/runtime-write
This PR adds below feature to the existing fio job
```
./fio_runner.sh --help
Usage :  fio_runner.sh --template
fio_runner.sh --size
fio_runner.sh --duration
fio_runner.sh --help	
fio_runner.sh --available_space
fio_runner.sh --miscellaneous
fio_runner.sh --read-only
fio_runner.sh --write-only
-h|--help    		Display this help and exit  
--template   		Select the fio template to run 
--size	     		Provide the data sample size (in Bytes as recomonded)
--duration   		Duration (in sec)
--available_space 	Get space left at mount point
--miscellaneous		Perform writes and reads on available space on given mount point
Ex: ./fio_runner.sh --available_space /datadir --miscellaneous /datadir(mount point)
--read-only		Perform Read on the filepath which is …
```
=> (Enhancement) Adds features to fio image

busybox/Dockerfile, busybox/liveness.sh
- Adds a busybox liveness script with associated Dockerfile.
- `liveness.sh` performs **CRUD** operation on busybox and for each CRUD-iteration it sets liveness running.
- `liveness.sh` takes pod-name, namespace, liveness_timeout, liveness_retry_count as environment variable.
**Following the log of the liveness-container**
```
10240+0 records in
10240+0 records out
41943040 bytes (40.0MB) copied, 0.431196 seconds, 92.8MB/s
liveness-running
Unable to use a TTY - input is not a terminal or the right kind of file
10240+0 records in
10240+0 records out
41943040 bytes (40.0MB) copied, 0.395782 seconds, 101.1MB/s
liveness-running
Unable to use a TTY - input is not a terminal or the right kind of file
10240+0 records in
10240+0 records out
41943040 bytes …
```
=> Added busybox client for liveness

linux-utils/Dockerfile, linux-utils/buildscripts/push
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
Bump alpine base image to 1.10.3 to fix some vulnerabilities.
=> fix(linux-utils): bump alpine base image to 3.10.3

.travis.yml, Makefile, app-cpu-stress/Dockerfile, app-cpu-stress/app-cpu-stress.yml, app-cpu-stress/buildscripts/push, app-cpu-stress/cpu-hog.sh, kafka-client/consumer.sh, kafka-client/producer.sh
- Resource chaos isolated to app-level can be invoked using a docker-in-docker container that mounts the docker socket (/var/run/docker.sock) file 
- The number of CPU cores, duration of chaos & Target Container ID are passed as environment variables to a CPU Stress Kubernetes job which is specified to run on a given node via a nodeSelector property. 
- The job deploys a DIND container that runs a shell script to asynchronously trigger multiple instances of the command `md5sum /dev/zero` depending on the number of CPU cores.
- After a period equalling the `DURATION`, the triggered processes are killed to stop the CPU chaos. 
**Notes** 
- While tools such as `stress-ng` are capable to achieving the same with greater options, it is necessary to inject …
=> Add CPU resource chaos job using DIND container

dd-client/Dockerfile, dd-client/README.md, dd-client/dd_client.yml, dd-client/io_runner.sh, tpcc-client/Dockerfile
Signed-off-by: shashank855 <ranjanshashank855@gmail.com>
- Adds a custom dd-client which act as generic loadgen client for kubernetes applications.
**Following the container log**:
```
Writing data on /var/lib/mysql
0+0 records in
0+0 records out
0 bytes copied, 0.000159033 s, 0.0 kB/s
Writing data on /var/lib/mysql
0+0 records in
0+0 records out
0 bytes copied, 0.000154041 s, 0.0 kB/s
Writing data on /var/lib/mysql
0+0 records in
0+0 records out
0 bytes copied, 7.1377e-05 s, 0.0 kB/s
Unable to get pod Name. Retrying...
Unable to get pod Name. Retrying...
Writing data on /var/lib/mysql
2+0 records in
2+0 records out
8192 bytes (8.2 kB, 8.0 KiB) copied, 0.000228296 s, 35.9 MB/s
Unable to get pod Name. Retrying...
Writing data on /var/lib/mysql
3+0 …
```
=> Refactor dd-client to make it generic for k8s applications

app_clients/nfs-client/Dockerfile, app_clients/nfs-client/nfs-mount-liveness-check.py, app_clients/nfs-client/nfs-mount-liveness-check.yaml
Signed-off-by: Raj <raj.das@mayadata.io>
Upgrading python version to 3 because the timeout parameter in subprocess.check_output requires python 3
Converting Indent from 8 spaces to 2 sapces
=> Upgrade(nfs-client): Upgrading python version to 3 in the nfs-client image

experiments/pod-delete/pod-delete.sh
- Fixing pod-delete helper image bash script
**Why these changes are required?**
- It was using the below command which doesn't evaluate the first condition 
```bash
if [[ -z ${kill_count} || ${kill_count} -eq 0 ]]; then
```
So changing to this seems to work fine and now it evaluates both of the conditions.
```bash
if [[ -z ${kill_count} ]] | [[ ${kill_count} -eq 0 ]]; then
```
Signed-off-by: Udit Gaurav <uditgaurav@gmail.com>
=> fix(pod-delete): Fixing pod-delete helper image bash script

custom/git-app-deployer/resilient-sock-shop.yaml, custom/git-app-deployer/weak-sock-shop.yaml
Updating manifest for sock-shop, removed user-load for sock-shop from installation app-deployer. 
With these changes, failures of the sock-shop application will stop.
=> Updating manifest for sock-shop

custom/litmus-checker/pkg/chaos-checker/check.go
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>
This PR updates the log message for stopped engine state in litmus-checker, this will provide more insight to the users incase there are no other experiment logs available.
=> Updated log message for stopped engine state

custom/git-app-deployer/Dockerfile, custom/git-app-deployer/loadtest.yaml, custom/git-app-deployer/main.go, custom/git-app-deployer/resilient-podtato-head.yaml, custom/git-app-deployer/weak-podtato-head.yaml
This PR is adding podtato-head application installation support for workflow installation.
Logs : 
```
W0412 06:23:29.254854       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time='2021-04-12T06:23:29Z' level=info msg='[Start]: Starting App Deployer...'
time='2021-04-12T06:23:29Z' level=info msg='[Status]: FilePath for App Deployer is resilient-podtato-head.yaml'
time='2021-04-12T06:23:29Z' level=info msg='[Status]: Namespace already exist'
time='2021-04-12T06:23:29Z' level=info msg='[Status]: Checking whether application containers are in ready state'
time='2021-04-12T06:23:43Z' level=info msg='[Status]: The running …
```
=> Added Podtato-head application for Pre-Defined Workflow installation

custom/git-app-deployer/main.go
- Added namespace scope flag for ```litmus-app-deployer```.
- Now supported for namespace/cluster scope installation.
- This flag is added to support namescope installation of litmus application and cluster scope as well.
- ```-scope=namescope``` will deploy(app-deployer) in agent namespace.  And for cluster scope will be in given namespace. 
=> Added namespace scope flag for litmus-app-deployer

custom/workflow-helper/app-deployer/Dockerfile, custom/workflow-helper/app-deployer/resilient-podtato-head.yaml, custom/workflow-helper/app-deployer/resilient-sock-shop.yaml, custom/workflow-helper/app-deployer/weak-podtato-head.yaml, custom/workflow-helper/app-deployer/weak-sock-shop.yaml
**This PR will add**
- Fix for App-deployer Dockerfile for Multiarch support.
- changes the default Service type for services pod-tato(main) and sockshop(frontend) from loadBalancer to NodePort.
=> Added Fix for App-deployer Dockerfile and Service type change

custom/hardened-alpine/experiment/Dockerfile
- This PR will update the Pumba image with version 0.8.0 which has the fix for the high-security vulnerability.
=> Chore(pumba): Fix image vulnerability of pumba with latest version 0.8.0

custom/hardened-alpine/experiment/Dockerfile, custom/hardened-alpine/infra/Dockerfile
CVEs list
```
Testing litmuschaos/infra-alpine...
✗ Medium severity vulnerability found in busybox/busybox
Description: CVE-2021-42375
Info: https://snyk.io/vuln/SNYK-ALPINE314-BUSYBOX-1915650
Introduced through: busybox/busybox@1.33.1-r3, alpine-baselayout/alpine-baselayout@3.2.0-r16, bash/bash@5.1.4-r0, ca-certificates/ca-certificates@20191127-r5, busybox/ssl_client@1.33.1-r3
From: busybox/busybox@1.33.1-r3
From: alpine-baselayout/alpine-baselayout@3.2.0-r16 > busybox/busybox@1.33.1-r3
From: bash/bash@5.1.4-r0 > busybox/busybox@1.33.1-r3
and 2 more... …
```
=> Updating base image of litmus-infra to alpine:3.15.0 due to some CVEs

custom/hardened-alpine/experiment/buildscripts/push
- Fix the release tag for pulling binaries in hardened alpine
=> Chore(release-tag): Fix the release tag for pulling binaries in hardened alpine

custom/hardened-alpine/experiment/Dockerfile
Signed-off-by: Akash Shrivastava <akash.shrivastava@harness.io>
This PR adds the toxiproxy server and client binaries to the `experiment-alpine` image for the HTTP chaos experiments.
=> Added toxiproxy to experiment-alpine image

custom/hardened-alpine/experiment/Dockerfile, custom/hardened-alpine/infra/Dockerfile
Signed-off-by: Jonsy13 <vedant.shrotria@harness.io>
**Before -** 
```
✗ Low severity vulnerability found in curl/libcurl
Description: CVE-2022-32221
Info: https://snyk.io/vuln/SNYK-ALPINE315-CURL-3063708
Introduced through: curl/libcurl@7.80.0-r3, curl/curl@7.80.0-r3
From: curl/libcurl@7.80.0-r3
From: curl/curl@7.80.0-r3 > curl/libcurl@7.80.0-r3
From: curl/curl@7.80.0-r3
Fixed in: 7.80.0-r4
✗ Low severity vulnerability found in curl/libcurl
Description: CVE-2022-42916
Info: https://snyk.io/vuln/SNYK-ALPINE315-CURL-3063709
Introduced through: curl/libcurl@7.80.0-r3, curl/curl@7.80.0-r3
From: …
```
=> Upgrading alpine image version to 3.16 for reducing vulnerabilities

custom/litmus-helm-agent/main.go, custom/litmus-helm-agent/pkg/litmus/client.go
Signed-off-by: Jonsy13 <vedant.shrotria@harness.io>
This PR will add support for skipping SSL verification 
- when communicating between `litmus-helm-agent` & `ChaosCenter`
- sets `SKIP_SSL_VERIFY`env accordingly for `subscriber` <-> `chaoscenter`
=> Added support for SKIP_SSL env in litmus-helm-agent

custom/mongo/Dockerfile, custom/mongo/buildscripts/push
**Update Mongo Image to version 6 - This is required because we need mongosh tool in 3.0.0 ChaosCenter wait init-container.**
=> Update Mongo Image to version 6

.github/workflows/release.yml, custom/hardened-alpine/experiment/Dockerfile, custom/nsutil/Dockerfile, custom/nsutil/cmd/root.go, custom/nsutil/nsutil.c, go.mod, go.sum
=> add local mount ns support to nsutil

custom/hardened-alpine/experiment/Dockerfile
- Fix the High Severity vulnerabilities found in Alpine 3.16.2:
https://nvd.nist.gov/vuln/detail/CVE-2023-0215
https://nvd.nist.gov/vuln/detail/CVE-2022-4450
https://nvd.nist.gov/vuln/detail/CVE-2023-0286 
**Which issue this PR fixes**: fixes #524 
**Special notes for your reviewer**: N/A
**Checklist:**
-   [x] Fixes #524 
-   [ ] PR messages has document related information
-   [ ] Labelled this PR & related issue with `breaking-changes` tag
-   [ ] PR messages has breaking changes related information
-   [ ] Labelled this PR & related issue with `requires-upgrade` tag
-   [ ] PR messages has upgrade related information
-   [ ] Commit has unit tests
-   [ ] Commit has integration tests
-   [ ] E2E run Required for the changes
=> Bumped Alpine version from 3.16.2 to 3.16.9 to fix vulnerabilities

custom/hardened-alpine/experiment/Dockerfile
This reverts commit 51597bca9c4f866532b5a3e1a95f3b14a5b64b0e.
=> Revert "Bumped Alpine version from 3.16.2 to 3.16.9 to fix vulnerabilities 

custom/litmus-helm-agent/pkg/k8s/client.go
=> Added litmusctl changes
