mongo-client/Dockerfile, mongo-client/server.py
This PR does the following:
1. Add a python script(server.py) for mongodb liveness check
2. Add a Dockerfile
Signed-off-by: ranjanshashank <ranjanshashank855@gmail.com>
=> Add a python script for mongo liveness check

custom-liveness-client/Dockerfile, custom-liveness-client/liveness.py
This PR does the following:
1. Add a python-script(liveness.py) for checking the liveness of an application on a cluster.
2. Docker file to build image
Signed-off-by: ranjanshashank <ranjanshashank855@gmail.com>
=> Add liveness-script for Custom Application

jenkins-client/Dockerfile, jenkins-client/jenkins-load-simulator.py
This PR does the following
1. Add a python script which act as a job simulator.
Signed-off-by: ranjanshashank <ranjanshashank855@gmail.com>
=> Add a python-script for jenkins-job-simulator

postgres-client/Dockerfile, postgres-client/liveness.py
Signed-off-by: sathyaseelan <sathyaseelan.n@cloudbyte.com>
- Written a Python script for liveness check on postgres statefulset
@ksatchit @dargasudarshan @gprasath can you please review this PR
=> Created Liveness script for crunchy postgres

postgres-client/Dockerfile, postgres-client/liveness/Dockerfile, postgres-client/liveness/liveness.py, postgres-client/workloads/Dockerfile
This PR does the following:
- Creates a single Docker file for both workloads & liveness of postgres.
=> Single docker file for both workload & liveness of postgres

Makefile
=> fix(makefile): provide proper image name while building postgresql client

README.md
I added a sample build badge on the README file using shields.io
=> Create the travis build pass badge on the test-tools README file #26

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
What this PR does / why we need it: To add this beautiful PR template in addition to the issue template, Signed-off-by: Florian Woerner <florian.woerner@onmyown.io> this time not like in the PR #31 
Which issue this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged): fixes #27
Special notes for your reviewer: Hope everything is all good, do not hesitate to comment :)
=> Add the issue & pull request template to test-tools repo

jenkins-client/test-jenkins-load-simulator.py
Added missing unit test for jenkins load simulator
**Which issue this PR fixes** 
Fixes #24
=> Issue #24: Create a unit test for the jenkins load simulator python script

custom-client/liveness.py
Signed-off-by: Aman Kumar Gupta <gupta2140@gmail.com>
This PR updates the comment lines, making them more readable.
=> Updated comments in liveness.py

postgres-client/Dockerfile
Optimizing and Reformatting postgres DockerFile. 
Issue linked with this PR: #43
=> Reformatting and optimizing postgres DockerFile

.travis.yml, dd-client/Dockerfile, dd-client/buildscripts/push, dd-client/io_runner.sh
Signed-off-by: Sudarshan <sudarshan.darga@cloudbyte.com>
- Include shell script to perform dd load from within the container
=> Include shell script to perform dd load from within the container

jupyter-scripts/generate_io.py, jupyter-scripts/test_download.py, jupyter-scripts/test_reader.py, jupyter-scripts/test_writer.py
Add tests for Reader Writer and download
Fix #23
=> Test generate_io script

mysql-client/Dockerfile
=> Refacored Docker file to incude Bareos package

jupyter-scripts/generate_io.py, jupyter-scripts/test_download.py
Signed-off-by: A V Rahul <a.v.rahul11@gmail.com>
=> [Fixed] linting ad import issues.

jupyter-scripts/generate_io.py
Signed-off-by: A V Rahul <a.v.rahul11@gmail.com>
=> [fixed] linting issues

.travis.yml, Makefile, sysbench/Dockerfile, sysbench/README.md, sysbench/buildscripts/push, sysbench/src/create_table.sql, sysbench/src/sysbench-runner.sh, sysbench/sysbench.conf
**What this PR does / why we need it**: Create a sysbench container based on the tpcc one
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #18 
**Special notes for your reviewer**: Hope it fits the need, sorry for the time it tooked.
=> Sysbench mysql test container

mysql-client/mysql-liveness-check.sh
- Add missing argument while calling usage function from script main
=> fix(bash)(liveness): add missing argument for usage

Makefile, memleak/Dockerfile, memleak/buildscripts/push, memleak/long_file.txt, memleak/memleak.py
Signed-off-by: Sudarshan <sudarshan.darga@cloudbyte.com>
- Include a docker file to fill out the memory.
- This image will be helpful to test the impact on the k8s environment due to memory constraint.
=>  Add a docker container which will fill out the memory

.travis.yml, Makefile, gitlab-runner/Dockerfile, gitlab-runner/buildscripts/build.sh, gitlab-runner/buildscripts/push
Signed-off-by: atulabhi <atulabhi@gmail.com>
What this PR does / why we need it:
This PR contains the dockerfile to build images which is need by gitlab-runner to run our E2E pipelines as well as the push script to push the image with latest tag on a successful build to openebs/kops dockerhub repo.
=> added dockerfile to build infra image for gitlab-runner

memleak/Dockerfile
Signed-off-by: vibhor995 <vibhor.kumar@mayadata.io>
1) Added missing long_file.txt into dockerfile required by memleak python script .
=> Added missing (COPY) long_file.txt file inside dockerfile required by memleak script.

fio/fio_runner.sh, fio/templates/file/basic-write
Signed-off-by: Utkarsh Mani Tripathi <utkarsh.tripathi@mayadata.io>
=> Add random write template

fio/fio_runner.sh
Signed-off-by: sathyaseelan <sathyaseelan.n@cloudbyte.com>
- Removed set -x verbose command from the script
=> refactor(script): Modified fio runner script

Makefile
Signed-off-by: vibhor995 <vibhor.kumar@mayadata.io>
1) Missing dependencies of memleak into Makefile for travis build.
=> Added missing memleak dependencies  in makefile script

.travis.yml, Makefile, busybox/buildscripts/push, busybox/liveness.sh, postgres-client/Dockerfile
- Adds a build script for busybox-liveness.
=> Added build script for busybox-liveness

busybox/buildscripts/push
=> Refactor Build script for busybox liveness

.travis.yml, Makefile, prometheus/Dockerfile, prometheus/buildscripts/push, prometheus/liveness.py
Adds build script for service liveness
- Added python script prometheus/liveness.py to check service liveness via socket connection
- Added Dockerfile to create  docker image for the 'service-liveness'  job pod
- Added prometheus/buildscripts/push  to create the 'service-liveness' docker image
- Edited Makefile and .travis.yml file
@gprasath @nsathyaseelan
=> Added prometheus liveness scripts

.travis.yml, Makefile, linux-utils/Dockerfile, linux-utils/buildscripts/push
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
=> feat(linux-utils): add alpine based linux utils docker image

jenkins-client/test-jenkins-load-simulator.py, prometheus/liveness.py
Signed-off-by: Nikita Titov <nekit94-12@hotmail.com>
use `assertEqual` from `unittest.TestCase` class in tests instead of simple `assert == ...`
=> use assertEqual in tests

.travis.yml, Makefile, kafka-client/Dockerfile, kafka-client/buildscripts/push, kafka-client/consumer.sh, kafka-client/producer.sh, kafka-client/topic.sh
Signed-off-by: ksatchit <ksatchit@mayadata.io>
- Includes a kafka-liveness client that sets up a simple pub-sub infrastructure.
- The message stream continuous of continuous output of date command 
=> (feat)image: include kafka-liveness client

kafka-client/consumer.sh, kafka-client/producer.sh
Signed-off-by: ksatchit <ksatchit@mayadata.io>
- Adds a kafka consumer timeout after which the consumer terminates
=> (refactor)kafka_scripts: update consumer script to accept message timeouts

minio-client/Dockerfile, minio-client/README.md, minio-client/job.yml, minio-client/main.go
Signed-off-by: shashank855 <shashank.ranjan@mayadata.io>
main.go is the primary execution script which runs in two mode based on environment variable passed.
- **liveness** mode which creates minio bucket and do the following operations
- Loads data in minio bucket.
- Unload minio bucket.
For each successful load and unload operation client says `Liveness Running`.
- **loadgen** mode which simply writes amount of data provided as env-variable. `Note: The exution time of loadgen mode may vary depending on the amount of data to be written `
- Keep main.go and docker file at **go-path** inside a same directory (ex: minio-client) and install the minio-client dependency by `GO111MODULE=on go get github.com/minio/minio-go/v6`.
- Then execute …
=> feat(add): minio-client for minio-application loadgen and liveness

NOTICE.md
Signed-off-by: ksatchit <ksatchit@mayadata.io>
- Adds license notice files for test tools
=> (chore)license: add license notice

.travis.yml, Makefile, app_clients/nfs-client/Dockerfile, app_clients/nfs-client/buildscripts/push, app_clients/nfs-client/nfs-mount-liveness-check.py, app_clients/nfs-client/nfs-mount-liveness-check.yaml
Signed-off-by: Raj <raj.das@mayadata.io>
Adding nfs client to check the volumes mounted using nfs
https://github.com/litmuschaos/litmus/issues/1302
=> Feat(nfs-client): Adding nfs client to check the volumes mounted using nfs

app_clients/cassandra-client/Dockerfile, app_clients/cassandra-client/buildscripts/push, app_clients/cassandra-client/cassandra-liveness-check.sh, app_clients/cassandra-client/cassandra-liveness-check.yaml, app_clients/cassandra-client/webserver.sh
- Adding Cassandra client for the liveness check of Cassandra statefulset by creation of keyspace,table,create rows,select rows,drop table, drop keyspace. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes litmuschaos/litmus#1362
=> feat(cassandra-client): Adding cassandra clients for liveness check

.travis.yml, Makefile
=> feat(cassandra-client): Building & Pushing cassandra-client image

custom/custom-client/custom-liveness.yml
Signed-off-by: Raj <raj.das@mayadata.io>
=> image changing to litmuschaos/custom-client

.travis.yml, Makefile, app_clients/kafka-client/Dockerfile, containerd/crictl/Dockerfile, containerd/crictl/buildscripts/push, containerd/crictl/crictl-kill.sh
- Adding the crictl image for container-kill experiment
=> feat(crictl): Adding the crictl image for container-kill experiment

.travis.yml, Makefile, containerd/crictl/Dockerfile, containerd/crictl/buildscripts/push, containerd/crictl/crictl-kill.sh, containerd/crictl/event.yaml
- Adding the events in crictl helper pod
=> feat(containerd): Adding the events in crictl helper pod

containerd/crictl/buildscripts/push
=> feat(containerd): updating the containerd image

experiments/pod-delete/pod-delete.sh
- Fixing image bash script for running pod-delete 
Signed-off-by: Udit Gaurav <uditgaurav@gmail.com>
=> fix(pod-delete): Fixing image bash script for running pod-delete 

experiments/pod-delete/pod-delete-event.yaml, experiments/pod-delete/pod-delete.sh
- fix jinja template for events in helper pod of pod delete experiment
=> fix(pod-delete): fix jinja template for events in helper pod of pod delete experiment

.travis.yml
- skip stages for docker images which weren't changed in the PR
- run docker build stages in parallel
- the goal: speed up the verification and build time: from ~ 30 mins -> 7.5 minutes
**Which issue this PR fixes**: 
fixes #100
No special notes
=> Refactor the travis ci to ensure only those images that are changed are built

custom/litmus-checker/Dockerfile
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>
Updated Litmus Checker to run as Non-Root User
=> Updated Litmus Checker to run as Non-Root User

.travis.yml, custom/promql-cli/README.md
=> chore(promql-cli): Creating image with promql-cli for promeProbe

custom/git-app-deployer/main.go
Signed-off-by: oumkale <oum.kale@mayadata.io>
Added revert application for Git-App-Deployer.
For sock-shop revert application has been added.
With ```operation``` flag.
=> [KUBC-363] Added revert application for App-deployer

custom/git-app-deployer/main.go, custom/git-app-deployer/resilient-sock-shop.yaml, custom/git-app-deployer/weak-sock-shop.yaml
(ephemeral-storage):Resources added for catalogue-db
For weak and resilient manifest
```
resources:
requests:
ephemeral-storage: "500Mi"
limits:
ephemeral-storage: "1Gi"
```
=> (ephemeral-storage):Resources added for catalogue-db

custom/git-app-deployer/main.go
Signed-off-by: oumkale <oum.kale@mayadata.io>
Namespace check added for app-deployer.
This PR resolve issue #146.
**Which issue this PR fixes** *`fixes #146` *: fixes #
=> Namespace check added for app-deployer

.travis.yml, Makefile, custom/k8s/Dockerfile, custom/k8s/buildscripts/push
Signed-off-by: Amit Kumar Das <amitkumar.das@mayadata.io>
**What this PR does / why we need it**: Added alpine/k8s:1.18.2 image for litmuschaos/k8s
=> Added alpine/k8s custom image

app_clients/kafka-client/consumer.sh, app_clients/kafka-client/producer.sh, app_clients/kafka-client/topic.sh
- Add logs for kafka liveness pod
=> Chore(logs): Add logs for kafka liveness pod

.travis.yml, Makefile, custom/git-app-deployer/git-app-checker/Dockerfile, custom/git-app-deployer/git-app-checker/buildscripts/push, custom/git-app-deployer/git-app-checker/main.py, custom/git-app-deployer/resilient-sock-shop.yaml, custom/git-app-deployer/weak-sock-shop.yaml
API checker send requests to ```/user, /catalogue, /details, /cards, /addresses, /basket``` endpoints.
Logs can be seen. We can see easily chaos injection change on endpoints easily using this api-checker.
With successfully case :+1: 
```
[Status]: API Checker has been started
[Status]: ResponseCode: 200  User successfully logged in
[Info]: Unique ID for user is: qcB5EZVSax5Gc1372Qzqnv__tK4dHXoW
[Info]: Sending request to front-end
[Status]: ResponseCode: 200  FrontEnd is accessible
[Info]: Adding new cutomer 
[Status]: ResponseCode: 200  Customer added successfully with user Name: test_user_cd74905e-0cd7-4d64-9fcb-38069d9f86de
[Status]: ResponseCode: 200  Catalogue get request successfully send
[Info]: Catalogue …
```
=> API Checker for sock-shop Application to track requests on endpoints

custom/git-app-deployer/resilient-sock-shop.yaml, custom/git-app-deployer/weak-sock-shop.yaml
This PR will update the image for app-checker to ```litmuschaos/litmus-git-app-checker```.
=> chore(app-checker):Litmus Git App Checker image updating

.travis.yml, Makefile, custom/argo-server/Dockerfile, custom/argo-server/buildscripts/push, custom/argo-workflow-controller/Dockerfile, custom/argo-workflow-controller/buildscripts/push, custom/argo-workflow-executor/Dockerfile, custom/argo-workflow-executor/buildscripts/push, custom/mongo/Dockerfile, custom/mongo/buildscripts/push
Adding argo-server, argo-workflow-controller and argo-executor to test-tools
=> Adding argo-server, argo-workflow-controller and argo-executor to test-tools

custom/dns_interceptor/README.md, custom/dns_interceptor/main.go, custom/dns_interceptor/server/interceptor.go, custom/dns_interceptor/server/types.go, custom/dns_interceptor/server/util.go
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>
This PR adds some minor fixes and custom server port and upstream server support to dns interceptor
=> Added custom port and custom upstream server support

build/go-multiarch-build.sh
=> Add script to build binary in actions

custom/workflow-helper/app-deployer/main.go
App deployer: Updating logs for errors
=> App deployer: Updating logs for errors

custom/scripts/push_images/README.md, custom/scripts/push_images/litmus_image_push.sh
=> Chore(image_push): Add script to push litmus image to the target image registry

.github/workflows/push.yml, Makefile, custom/argo-server/Dockerfile, custom/argo-server/buildscripts/push, custom/argo-workflow-controller/Dockerfile, custom/argo-workflow-controller/buildscripts/push, custom/argo-workflow-executor/Dockerfile, custom/argo-workflow-executor/buildscripts/push, custom/k8s/Dockerfile, custom/k8s/buildscripts/push, custom/litmus-checker/Dockerfile, custom/workflow-helper/app-checker/Dockerfile, custom/workflow-helper/app-checker/buildscripts/push, custom/workflow-helper/app-deployer/Dockerfile, custom/workflow-helper/app-qps-test/Dockerfile
This PR will update the images for controller and executor.
Also, will add the multiarch support for 
- k8s:latest
- litmus-checker
- litmus-git-app-checker
- app-qps-test
- app-deployer
- app-checker
=> Upgraded the Images for Workflow executor and controller.

custom/k8s/buildscripts/push, custom/workflow-helper/app-deployer/Dockerfile
This PR will add a Minor fix in the k8s Image push script.
=> Added build fix for k8s and app-deployer for multiarch images

custom/workflow-helper/README.md, custom/workflow-helper/app-checker/README.md, custom/workflow-helper/app-deployer/README.md, custom/workflow-helper/app-qps-test/README.md
README for app-deployer, app-checker and app-qps-tester
=> README for app-deployer, app-checker and app-qps-tester

.github/workflows/build.yml, .github/workflows/push.yml, Makefile, custom/curl/Dockerfile, custom/curl/buildscripts/push
**This PR will add a multi-arch image for curl binary. This is needed to be used in initContainer in server deployment of Portal.**
=> Added curl image in test-tools

io_tools/fortio/fortio.yaml
Signed-off-by: shubham chaudhary <shubham@chaosnative.com>
=> chore(fortio): Adding fortio manifest for load generation

custom/argo-workflow-controller/Dockerfile, custom/argo-workflow-controller/buildscripts/push, custom/argo-workflow-executor/Dockerfile, custom/argo-workflow-executor/buildscripts/push
This PR will update workflow controller & argoexec images to v3.2.3.
=> Updating workflow controller & argoexec images to v3.2.3

custom/hardened-alpine/experiment/Dockerfile
=> Chore(openshift): Fix the directory permission of experiment image for openshift cluster

custom/hardened-alpine/experiment/Dockerfile
- This PR will use the updated the promql binary in experiment base images that have no high or critical vulnerabilities.
=> Chore(experiment-image): Update the promql binary in experiment base image

custom/workflow-helper/postgres-helper/jmeter/Dockerfile
Upgrading Jmeter version to 5.4.2
migrating base image  to alpine because https://www.centos.org/centos-linux-eol/
=> Upgrading Jmeter version to 5.4.2 & migrating base image  to alpine

custom/workflow-helper/postgres-helper/jmeter/Dockerfile
=> Update URL in the docker file of litmus-pg-jmeter

custom/hardened-alpine/experiment/Dockerfile
- Fix experiment hardened alpine vulnerability
- Package updated is: `expat-doc`
=> Chore(vulnerability): Fix experiment hardened alpine vulnerability

app_clients/kafka-client/Dockerfile
* Upgrading confluentinc/cp-enterprise-kafka to 7.0.1
* Fixing CVEs
=> Upgrading confluentinc/cp-enterprise-kafka to 7.0.1

custom/curl/Dockerfile
**This PR will update the curl image version.**
=> Updated the curl image version

.github/workflows/build.yml, .github/workflows/push.yml, Makefile, custom/workflow-helper/README.md, custom/workflow-helper/postgres-helper/monitoring/prometheus/02-prometheus-configMap.yaml, custom/workflow-helper/redis-helper/README.md, custom/workflow-helper/redis-helper/load-gen/Dockerfile, custom/workflow-helper/redis-helper/load-gen/buildscripts/push, custom/workflow-helper/redis-helper/load-gen/locustfile.py, custom/workflow-helper/redis-helper/load-gen/redis-cmd.py, custom/workflow-helper/redis-helper/load-gen/redisLoad.py, custom/workflow-helper/redis-helper/manifest/dashboard.json, custom/workflow-helper/redis-helper/manifest/deployment.yaml, custom/workflow-helper/redis-helper/manifest/redisLoadDeployment.yaml, custom/workflow-helper/redis-helper/manifest/redisLoadLocustDeployment.yaml, custom/workflow-helper/redis-helper/manifest/statefulset.yaml
- Adding redis helper for redis resiliency workflow
- Redis Dashboard
- Cmd probe checker
=> Adding redis helper for redis resiliency workflow

.github/workflows/build.yml, .github/workflows/push.yml, Makefile, custom/security/snyk/Dockerfile, custom/security/snyk/buildscripts/push
- Add dockerfile for snyk image to run code scan in all the repos.
=> Chore(snyk): Add litmus snyk image to run code scan on repos

.github/workflows/release.yml
**This PR will add tagged image for mongo-utils** 
=> Added tagged image for mongo-utils

custom/security/snyk/Dockerfile
- Add python in litmus snyk image
=> Chore(snyk): Add python in litmus snyk image

custom/argo-workflow-controller/Dockerfile, custom/argo-workflow-controller/buildscripts/push, custom/argo-workflow-executor/Dockerfile, custom/argo-workflow-executor/buildscripts/push
**This PR will upgrade Argo workflow-controller & executor to `v3.2.9` for fixing some of the vulnerabilities.**
=> Upgrading Argo workflow-controller & executor to v3.2.9

.github/workflows/build.yml, .github/workflows/push.yml, Makefile, custom/litmusctl/Dockerfile, custom/litmusctl/buildscripts/push
Signed-off-by: Vedant Shrotria <vedant.shrotria@harness.io>
=> Added docker image for litmusctl

.github/workflows/push.yml, custom/hardened-alpine/experiment/Dockerfile, custom/hardened-alpine/experiment/buildscripts/push, go.mod
This PR updates the toxiproxy binary source paths
=> Updates Toxiproxy binaries source paths

custom/argo-workflow-controller/Dockerfile, custom/argo-workflow-controller/buildscripts/push, custom/argo-workflow-executor/Dockerfile, custom/argo-workflow-executor/buildscripts/push
Signed-off-by: Vedant <vedant.srotria@harness.io>
=> Added changes for 3.3.1 argo upgrade

custom/dns_interceptor/server/util.go
Signed-off-by: Vedant <vedant.srotria@harness.io>
=> Added minor change for ignoring loopback check for nameservers in dns interceptors

io_tools/fortio/fortio.yaml
=> Chore(template): Adds label in fortio template

custom/hardened-alpine/experiment/Dockerfile
Signed-off-by: Shubham Chaudhary <shubham.chaudhary@harness.io>
=> fix(vuln): removing pumba binary and updating promql cli version

.github/workflows/push.yml, Makefile, custom/security/snyk/Dockerfile
=> fix(snyk): Remove the SNYK_TOKEN from args and env

custom/argo-server/buildscripts/push, custom/argo-workflow-controller/buildscripts/push, custom/argo-workflow-executor/buildscripts/push, custom/curl/buildscripts/push, custom/hardened-alpine/experiment/buildscripts/push, custom/hardened-alpine/infra/buildscripts/push, custom/k8s/buildscripts/push, custom/litmus-checker/buildscripts/push, custom/litmus-helm-agent/buildscripts/push, custom/litmusctl/buildscripts/push, custom/mongo-utils/buildscripts/push, custom/mongo/buildscripts/push, custom/workflow-helper/app-checker/buildscripts/push, custom/workflow-helper/app-deployer/buildscripts/push, custom/workflow-helper/app-qps-test/buildscripts/push, custom/workflow-helper/postgres-helper/jmeter/buildscripts/push, custom/workflow-helper/postgres-helper/load-test/buildscripts/push, custom/workflow-helper/redis-helper/load-gen/buildscripts/push
=> fixed --progress=plane flag in all docker commands

custom/hardened-alpine/experiment/Dockerfile
=> fix(promql): update the promql version

.github/workflows/push.yml
=> Fixed push pipeline for litmus-helm-agent

custom/hardened-alpine/infra/Dockerfile
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-ALPINE316-OPENSSL-3314624
- https://snyk.io/vuln/SNYK-ALPINE316-OPENSSL-3314624
- https://snyk.io/vuln/SNYK-ALPINE316-OPENSSL-3314641
- https://snyk.io/vuln/SNYK-ALPINE316-OPENSSL-3314641
- https://snyk.io/vuln/SNYK-ALPINE316-OPENSSL-3314643
=> [cherrypick for 3..6.1]

custom/hardened-alpine/infra/Dockerfile
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-ALPINE316-OPENSSL-3314624
- https://snyk.io/vuln/SNYK-ALPINE316-OPENSSL-3314624
- https://snyk.io/vuln/SNYK-ALPINE316-OPENSSL-3314641
- https://snyk.io/vuln/SNYK-ALPINE316-OPENSSL-3314641
- https://snyk.io/vuln/SNYK-ALPINE316-OPENSSL-3314643
=> fix: custom/hardened-alpine/infra/Dockerfile to reduce vulnerabilities

custom/hardened-alpine/experiment/Dockerfile
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/litmuschaos/litmus/issues/4605
=> Fix vulnerability in crictl in hardend alpine image

.github/workflows/release.yml, custom/hardened-alpine/experiment/Dockerfile, custom/nsutil/Dockerfile, custom/nsutil/cmd/root.go, custom/nsutil/nsutil.c, go.mod, go.sum
=> add mount ns support to nsutil (#499)

custom/hardened-alpine/experiment/Dockerfile
=> fix(nsutil): fix the nsutil shared lib path

custom/hardened-alpine/experiment/Dockerfile
=> fix(nsutil): fix the nsutil shared lib path (#501)

custom/litmus-checker/go.mod, custom/litmus-checker/go.sum, custom/litmus-checker/main.go, custom/litmus-checker/pkg/chaos-checker/check.go, custom/litmus-checker/pkg/k8s/client.go, custom/litmus-checker/pkg/util/utils.go
=> fix(logs): Improve the litmus-checker logs
